### Introduction to data
Some define Statistics as the field that focuses on turning information into knowledge. The first step in that process is to summarize and describe the raw information - the data. In this lab, you will gain insight into public health by generating simple graphical and numerical summaries of a data set collected by the Centers for Disease Control and Prevention (CDC). As this is a large data set, along the way you'll also learn the indispensable skills of data processing and subsetting.

### Getting started
The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey of 350,000 people in the United States. As its name implies, the BRFSS is designed to identify risk factors in the adult population and report emerging health trends. For example, respondents are asked about their diet and weekly physical activity, their HIV/AIDS status, possible tobacco use, and even their level of healthcare coverage. The BRFSS Web site (http://www.cdc.gov/brfss) contains a complete description of the survey, including the research questions that motivate the study and many interesting results derived from the data.

We will focus on a random sample of 20,000 people from the BRFSS survey conducted in 2000. While there are over 200 variables in this data set, we will work with a small subset.

We begin by importing the dataset of 20,000 observations from the Cloud.

In [1]:
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)): 
    ssl._create_default_https_context = ssl._create_unverified_context

In [2]:
import pandas as pd

cdc = pd.read_csv('https://www.openintro.org/stat/data/cdc.csv')
cdc

,genhlth,exerany,hlthplan,smoke100,height,weight,wtdesire,age,gender
0,good,0,1,0,70,175,175,77,m
1,good,0,1,1,64,125,115,33,f
2,good,1,1,1,60,105,105,49,f
3,good,1,1,0,66,132,124,42,f
4,very good,0,1,0,61,150,130,55,f
5,very good,1,1,0,64,114,114,55,f
6,very good,1,1,0,71,194,185,31,m
7,very good,0,1,0,67,170,160,45,m
8,good,0,1,1,65,150,130,27,f
9,good,1,1,0,70,180,170,44,m
10,excellent,1,1,1,69,186,175,46,m
11,fair,1,1,1,69,168,148,62,m
12,excellent,1,0,1,66,185,220,21,m
13,excellent,1,1,1,70,170,170,69,m
14,fair,1,0,0,69,170,170,23,m
15,good,1,1,1,73,185,175,79,m
16,good,0,0,1,67,156,150,47,m
17,fair,0,1,1,71,185,185,76,m
18,good,1,1,1,75,200,190,43,m
19,very good,1,1,0,67,125,120,33,f
20,very good,1,1,0,69,200,150,48,f
21,good,1,1,1,65,160,140,54,f
22,very good,0,1,1,73,160,160,43,m
23,good,1,1,1,67,165,158,30,m
24,very good,0,0,1,64,105,120,27,f
25,good,0,1,0,68,190,150,33,f
26,excellent,1,0,1,67,190,165,44,f
27,excellent,1,0,1,69,160,150,42,f
28,very good,1,1,0,61,115,105,32,f
29,excellent,1,1,1,74,185,175,63,m
...,...,...,...,...,...,...,...,...,...
19970,excellent,1,1,0,73,168,178,19,m
19971,very good,1,0,1,59,85,100,36,f
19972,excellent,1,1,1,65,145,135,42,f
19973,fair,1,1,0,67,110,120,35,f
19974,good,0,1,0,66,156,150,79,f
19975,fair,1,1,0,65,230,190,45,m
19976,good,1,1,0,67,198,140,39,f
19977,very good,0,1,1,65,180,150,87,f
19978,good,0,1,1,64,135,135,39,m
19979,good,1,1,0,69,265,200,28,m
19980,excellent,1,1,1,75,195,195,36,m
19981,very good,0,1,1,74,210,210,40,m
19982,very good,1,0,1,63,171,130,31,f
19983,very good,1,1,1,71,190,180,41,m
19984,good,1,1,1,69,180,160,57,m
19985,very good,1,1,1,64,120,115,71,f
19986,excellent,1,1,1,63,140,115,38,f
19987,good,1,1,0,72,200,195,40,m
19988,very good,1,1,1,74,230,190,53,m
19989,good,1,1,0,73,230,200,38,m
19990,excellent,1,1,0,71,195,190,43,m
19991,very good,1,1,1,72,210,175,52,m
19992,very good,1,1,0,71,180,180,36,m
19993,very good,0,1,1,63,165,120,31,f
19994,good,0,1,1,69,224,224,73,m
19995,good,1,1,0,66,215,140,23,f
19996,excellent,0,1,0,73,200,185,35,m
19997,poor,0,1,0,65,216,150,57,f
19998,good,1,1,0,67,165,165,81,f
19999,good,1,1,1,69,170,165,83,m


The data set cdc that shows up is a data matrix, with each row representing a case and each column representing a variable. These kind of data format are called data frame, which is a term that will be used throughout the labs.

To view the names of the variables, use columns.values

In [3]:
cdc.columns.values

array(['genhlth', 'exerany', 'hlthplan', 'smoke100', 'height', 'weight',
       'wtdesire', 'age', 'gender'], dtype=object)

This returns the names genhlth, exerany, hlthplan, smoke100, height, weight, wtdesire, age, and gender. Each one of these variables corresponds to a question that was asked in the survey. For example, for genhlth, respondents were asked to evaluate their general health, responding either excellent, very good, good, fair or poor. The exerany variable indicates whether the respondent exercised in the past month (1) or did not (0). Likewise, hlthplan indicates whether the respondent had some form of health coverage (1) or did not (0). The smoke100 variable indicates whether the respondent had smoked at least 100 cigarettes in her lifetime. The other variables record the respondent’s height in inches, weight in pounds as well as their desired weight, wtdesire, age in years, and gender.

In [4]:
cdc.head()

,genhlth,exerany,hlthplan,smoke100,height,weight,wtdesire,age,gender
0,good,0,1,0,70,175,175,77,m
1,good,0,1,1,64,125,115,33,f
2,good,1,1,1,60,105,105,49,f
3,good,1,1,0,66,132,124,42,f
4,very good,0,1,0,61,150,130,55,f

In [5]:
cdc.tail()

,genhlth,exerany,hlthplan,smoke100,height,weight,wtdesire,age,gender
19995,good,1,1,0,66,215,140,23,f
19996,excellent,0,1,0,73,200,185,35,m
19997,poor,0,1,0,65,216,150,57,f
19998,good,1,1,0,67,165,165,81,f
19999,good,1,1,1,69,170,165,83,m

In [6]:
cdc['weight'].describe()

count    20000.00000
mean       169.68295
std         40.08097
min         68.00000
25%        140.00000
50%        165.00000
75%        190.00000
max        500.00000
Name: weight, dtype: float64

In [7]:
190 - 140

50

In [14]:
cdc.length

AttributeError: 'DataFrame' object has no attribute 'length'

In [9]:
length(cdc)

NameError: name 'length' is not defined